version: '3.9'
services:
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: toyskid_project
      MYSQL_USER: dott
      MYSQL_PASSWORD: dbPass@123
      MYSQL_ROOT_PASSWORD: 123@123Aa

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin
      environment:
        PMA_HOST: db
      ports:
        - '8080:80'
      restart: always
      network:
        - mynetwork
      depends_on:
        - db
networks:
  my-network:
    driver: bridge